import type { Evidencia } from '@/lib/tipos'

export const evidenciasSemilla: Evidencia[] = [
  {
    id: 'ev-001',
    nombre: 'Actas de comité curricular',
    programaId: 'prog-der',
    periodo: '2025-1',
    factor: 'Factor 4 · Procesos académicos',
    indicador: 'Indicador 4.1 · Pertinencia curricular',
    estado: 'Validado',
    autorId: 'usr-cargador',
    nombreArchivo: 'actas-comite-curricular.pdf',
    fechaCarga: '2026-08-25',
  },
  {
    id: 'ev-002',
    nombre: 'Plan de mejoramiento 2026',
    programaId: 'prog-med',
    periodo: '2026-1',
    factor: 'Factor 10 · Mejoramiento',
    indicador: 'Indicador 10.2 · Seguimiento al plan',
    estado: 'Borrador',
    autorId: 'usr-cargador',
    nombreArchivo: 'plan-mejoramiento-2026.xlsx',
    fechaCarga: '2026-08-22',
  },
  {
    id: 'ev-003',
    nombre: 'Resultados pruebas Saber Pro',
    programaId: 'prog-isw',
    periodo: '2025-2',
    factor: 'Factor 5 · Profesores',
    indicador: 'Indicador 5.3 · Desempeño estudiantil',
    estado: 'Validado',
    autorId: 'usr-cargador',
    nombreArchivo: 'resultados-saber-pro.pdf',
    fechaCarga: '2026-08-18',
  },
  {
    id: 'ev-004',
    nombre: 'Seguimiento a egresados',
    programaId: 'prog-ade',
    periodo: '2024-2',
    factor: 'Factor 7 · Egresados',
    indicador: 'Indicador 7.1 · Inserción laboral',
    estado: 'Rechazado',
    autorId: 'usr-cargador',
    nombreArchivo: 'seguimiento-egresados.xlsx',
    fechaCarga: '2026-08-10',
    observaciones: 'Falta la fuente de datos y la periodicidad del indicador.',
  },
  {
    id: 'ev-005',
    nombre: 'Informe de autoevaluación institucional',
    programaId: 'prog-isw',
    periodo: '2024-2',
    factor: 'Factor 1 · Proyecto educativo',
    indicador: 'Indicador 1.2 · Alineación curricular',
    estado: 'Borrador',
    autorId: 'usr-cargador',
    nombreArchivo: 'informe-autoevaluacion.pdf',
    fechaCarga: '2026-08-28',
  },
]
