import type { Plantilla } from '@/lib/tipos'

/** Alineado con archivos en FormatosGuia/ y seed backend. */
export const plantillasSemilla: Plantilla[] = [
  {
    id: 'plt-guia-ci',
    nombre: 'Documento Maestro — Condiciones institucionales',
    factor: 'CI · Autoevaluación institucional',
    formato: 'DOCX',
    version: '2026.1',
    vigente: true,
    categoria: 'Institucional',
    tipoTramite: 'General',
    esGuiaDocumentoMaestro: true,
    descripcion:
      'Guía: Informe de Autoevaluación de Condiciones Institucionales (CI).',
    nombreArchivo:
      'Informe de Autoevaluación de Condiciones Institucionales (CI).docx',
  },
  {
    id: 'plt-guia-cp-ren',
    nombre: 'Documento Maestro — Condiciones de programa (Renovación)',
    factor: 'CP · Renovación de registro calificado',
    formato: 'DOCX',
    version: '2026.1',
    vigente: true,
    categoria: 'Programa',
    tipoTramite: 'Renovacion',
    esGuiaDocumentoMaestro: true,
    descripcion: 'Guía del documento maestro para procesos de renovación.',
    nombreArchivo: 'Documento Maestro (Condiciones de Programa).docx',
  },
  {
    id: 'plt-guia-cp-nuevo',
    nombre: 'Documento Maestro — Condiciones de programa (Nuevo)',
    factor: 'CP · Creación de programa',
    formato: 'DOCX',
    version: '2026.1',
    vigente: true,
    categoria: 'Programa',
    tipoTramite: 'NuevoPrograma',
    esGuiaDocumentoMaestro: true,
    descripcion: 'Guía para programas de primera vez (Plan de Desarrollo).',
    nombreArchivo: 'Plan de Desarrollo (solo para primera vez).docx',
  },
  {
    id: 'plt-auto-ren',
    nombre: 'Evidencias de autoevaluación de programa (Renovación)',
    factor: 'Autoevaluación · Renovación',
    formato: 'DOCX',
    version: '2026.1',
    vigente: true,
    categoria: 'Autoevaluacion',
    tipoTramite: 'Renovacion',
    esGuiaDocumentoMaestro: false,
    descripcion: 'Matriz de evidencias para renovación.',
    nombreArchivo: 'Evidencias de Autoevaluación de Programa (Renovación).docx',
  },
  {
    id: 'plt-contingencia',
    nombre: 'Plan de contingencia',
    factor: 'CI · Gestión de riesgos',
    formato: 'DOCX',
    version: '2026.1',
    vigente: true,
    categoria: 'Institucional',
    tipoTramite: 'General',
    descripcion: 'Formato de plan de contingencia institucional.',
    nombreArchivo: 'Plan de Contingencia.docx',
  },
  {
    id: 'plt-modificacion',
    nombre: 'Solicitud de modificación',
    factor: 'CP · Modificación curricular',
    formato: 'DOCX',
    version: '2026.1',
    vigente: true,
    categoria: 'Programa',
    tipoTramite: 'General',
    descripcion: 'Solicitud de modificación de programa.',
    nombreArchivo: 'Solicitud de Modificación.docx',
  },
]
